# -*- coding: utf-8 -*-
"""
Created on Thu Jan 23 19:39:16 2020

@author: cyrzon
"""
import pandas as pd
all_fallacies = pd.DataFrame({'being_right':['right',
               'was right',
               'correct',
               'wrong',
               'prove',
               'explain',
               'point',
               'to prove',
               'feelings',
               'arguing'
        ],

'blaming': ['blame',
           'blamed',
           'blaming',
           'blame my',
           'fault',
           'my',
           'blamed my',
           'for not',
           'for',
           'because'],

'catastophizing': ['what if',
                  'started',
                  'worry',
                  'die',
                  'panicked',
                  'will',
                  'worried',
                  'what',
                  'panic',
                  'going to'],

'control_fallacy':['control',
                   'responsible',
                   'responsible for',
                   'help',
                   'of control',
                   'felt',
                   'to help',
                   'feel responsible',
                   'feel',
                   'advice' ],

'emotional_reasoning': ['feel',
                       'felt',
                       'invited',
                       'me',
                       'invite',
                       'guilty',
                       'emotions',
                       'go',
                       'but',
                       'feeling'],

'change_fallacy': ['change',
                  'happy',
                  'to change',
                  'relationship',
                  'be happy',
                  'if',
                  'happiness',
                  'would',
                  'him',
                  'happier'],

'fairness_fallacy':  ['unfair',
                    'fair',
                    'unfair that',
                    'fair that',
                    'resentful',
                    'was unfair',
                    'pulled',
                    'got',
                    'people',
                    'ticket'],

'filtering': ['negative',
             'great',
             'positive',
             'good',
             'said',
             'on',
             'but',
             'comment',
             'focus',
             'nice'],

'global_labelling': ['internal',
                    'external',
                    'met',
                    'concluded',
                    'concluded that',
                    'loser',
                    'women',
                    'people',
                    'men',
                    'decided'],

'heavens_reward_fallacy': ['cheated',
                          'worked',
                          'hard',
                          'bitter',
                          'shocked',
                          'deserved',
                          'put',
                          'that if',
                          'rewarded',
                          'sacrifice'],

'mind_reading': ['assume',
                'assumed',
                'convinced',
                'response',
                'reply',
                'she',
                'respond',
                'at me',
                'they',
                'read'],

'overgeneralization': ['never',
                      'always',
                      'again',
                      'would never',
                      'will',
                      'ever',
                      'will always',
                      'now',
                      'because',
                      'i will never' ],

'personalization':['happy for',
                   'compare',
                   'jealous',
                   'why',
                   'my friend',
                   'friend',
                   'friend got',
                   'compared',
                   'compare myself',
                   'myself'],


'polarized_thinking': ['failure',
                      'either',
                      'perfect',
                      'if',
                      'failed',
                      'or',
                      'score',
                      'or nothing',
                      'pefectly',
                      'goal'],

'shoulds': ['should',
           'people should',
           'that should',
           'should be',
           'people',
           'rules',
           'should always',
           'believe',
           'believed',
           'college']
})